TEACHER_TITLE_PRE = 1
TEACHER_NAME = 2
TEACHER_SURNAME = 3
TEACHER_TITLE_POST = 4
TEACHER_KV = 5
TEACHER_KVSTV = 6
TEACHER_SUBJECTS = 7
TEACHER_COURSES_1 = 8
TEACHER_COURSES_2 = 9
TEACHER_COORDINATOR = 10
TEACHER_OFFICEHOUR_DAY = 11
TEACHER_OFFICEHOUR_LESSON = 12
TEACHER_AFTERNOON = 13
TEACHER_REMARKS = 14
TEACHER_NOIMG = 15

#TODO : Admin personnel
ADMIN_FUNCTION = 0
ADMIN_TITLE_PRE = 1
ADMIN_NAME = 2
ADMIN_SURNAME = 3
ADMIN_TITLE_POST = 4