TEACHER_TITLE_PRE = 1
TEACHER_NAME = 2
TEACHER_SURNAME = 3
TEACHER_TITLE_POST = 4
TEACHER_KV = 5
TEACHER_KVSTV = 6
TEACHER_UNTIS = 7
TEACHER_SUBJECTS = 8
TEACHER_COURSES_1 = 9
TEACHER_COURSES_2 = 10
TEACHER_COORDINATOR = 11
TEACHER_OFFICEHOUR_DAY = 12
TEACHER_OFFICEHOUR_LESSON = 13
TEACHER_OFFICEHOUR_ROOM = 14
TEACHER_AFTERNOON = 15
TEACHER_IMG = 16
TEACHER_REMARKS = 17

#TODO : Admin personnel
ADMIN_FUNCTION = 0
ADMIN_TITLE_PRE = 1
ADMIN_NAME = 2
ADMIN_SURNAME = 3
ADMIN_EMAIL = 4
ADMIN_TEL = 5
ADMIN_OFFICEHOUR = 6
